### PR TITLE
Address deprecation warnings

### LINKED ISSUE #16: Fix deprecation warnings
Running `pytest` returns 3733 warnings

### PR DESCRIPTION
**Pull request by kushaangupta**
Closes #16

### CODE REVIEW

**Comment by ryanharvey1** [comment]
Scipy wants us to use PyWavelets for morlet instead of scipy.signal.morlet. We can switch and add to requirements.

**Comment by kushaangupta** [comment]
I think the biggest problem for deprecation warnings comes from the nelpy. Maybe we should address that too in your fork

**Comment by ryanharvey1** [comment]
> I think the biggest problem for deprecation warnings comes from the nelpy. Maybe we should address that too in your fork

Working on this now.

**Comment by kushaangupta** [comment]
Stale, the number of warnings has reduced. Maybe we address the final few and merge it

**Comment by ryanharvey1** [comment]
> Scipy wants us to use PyWavelets for morlet instead of scipy.signal.morlet. We can switch and add to requirements. 

This represents the vast majority of warnings because the test is calling it 4000 something times.

**Pull request closed without merging**
