### PR TITLE
Comparative population geodynamics

### LINKED ISSUE #35: Add functions to compute similarity of dynamics and proximity between two neural trajectories
Refer: Guidera, J. A., Gramling, D. P., Comrie, A. E., Joshi, A., Denovellis, E. L., Lee, K. H., Zhou, J., Thompson, P., Hernandez, J., Yorita, A., Haque, R., Kirst, C., & Frank, L. M. (2024). Regional specialization manifests in the reliability of neural population codes. bioRxiv : the preprint server for biology, 2024.01.25.576941. https://doi.org/10.1101/2024.01.25.576941

### PR DESCRIPTION
**Pull request by kushaangupta**
Closes #35

### CODE REVIEW

**Comment by ryanharvey1** [comment]
Pulling main into your PR caused my new spatial map tests to fail? Very odd, because they were passing before. 

#47

**Comment by kushaangupta** [comment]
interesting that it passed for 3.9

**Comment by ryanharvey1** [comment]
I re-started the test that failed above in 3.11, and it all passed. I guess there was some randomness that I didn't account for in the test. 

We could merge this PR and deal with that test afterward in a separate PR.

**Comment by kushaangupta** [comment]
Sounds good

**Pull request merged**
